import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FiMenu } from "react-icons/fi";
import { FaStar } from "react-icons/fa";
import React from "react";
import { LuBeef } from "react-icons/lu";
import { BiSolidBowlHot } from "react-icons/bi";
import { IoFish } from "react-icons/io5";
import { GiShrimp } from "react-icons/gi";
import { IoWineSharp } from "react-icons/io5";
import { LuCakeSlice } from "react-icons/lu";
import { FaBellConcierge } from "react-icons/fa6";
const inter = Inter({ subsets: ["latin"] });

const icons = [
    { icon: <FiMenu />, text: "Menu" },
    { icon: <FaStar />, text: "Star" },
    { icon: <BiSolidBowlHot />, text: "Solid Bowl Hot" },
    { icon: <LuBeef />, text: "Beef" },
    { icon: <IoFish />, text: "Fish" },
    { icon: <GiShrimp />, text: "Shrimp" },
    { icon: <IoWineSharp />, text: "Wine Sharp" },
    { icon: <LuCakeSlice />, text: "Cake Slice" },
    { icon: <FaBellConcierge />, text: "Bell Concierge" },
];
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="nav bg-[#f6f7fb] w-screen h-screen flex overflow-hidden">
                    <div className="bg-[#4f565e]  flex-col justify-center ">
                        <ul className=" flex flex-col flex-1">
                            {icons.map((item, index) => (
                                <li
                                    key={index}
                                    className="mx-auto items-center text-2xl flex-1"
                                >
                                    <button
                                        className={`p-6 mt-1 mb-1 flex-1 ${
                                            index !== icons.length - 1
                                                ? "border-b border-gray-800"
                                                : ""
                                        } text-[#babbbe]`}
                                    >
                                        {item.icon}
                                    </button>
                                </li>
                            ))}
                        </ul>
                    </div>{" "}
                    <div>{children} </div>
                </div>
            </body>
        </html>
    );
}
