import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FiMenu } from "react-icons/fi";
import { FaStar } from "react-icons/fa";
import React from "react";
import { LuBeef } from "react-icons/lu";
import { BiSolidBowlHot } from "react-icons/bi";
import { IoFish } from "react-icons/io5";
import { GiShrimp } from "react-icons/gi";
import { IoWineSharp } from "react-icons/io5";
import { LuCakeSlice } from "react-icons/lu";
import { FaBellConcierge } from "react-icons/fa6";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="nav bg-[#f6f7fb] w-screen h-screen flex">
                    <div className=" bg-[#4f565e] w-20 h-fit flex-col justify-center">
                        <ul className=" flex flex-col ">
                            <li className=" mx-auto items-center text-2xl ">
                                <button className=" p-6 border-b border-gray-800  text-[#babbbe]">
                                    <FiMenu />
                                </button>
                            </li>
                            <li className=" mx-auto items-center  text-2xl">
                                <button className=" p-6 pt-[60px] border-b border-gray-800  text-[#babbbe]">
                                    <FaStar />
                                </button>
                            </li>{" "}
                            <li className=" mx-auto items-center text-2xl">
                                <button className=" p-6 border-b border-gray-800 text-[#babbbe]">
                                    <BiSolidBowlHot />
                                </button>
                            </li>{" "}
                            <li className=" mx-auto items-center text-2xl">
                                <button className=" p-6 border-b border-gray-800 text-[#babbbe]">
                                    <LuBeef />
                                </button>
                            </li>{" "}
                            <li className=" mx-auto items-center text-2xl">
                                <button className=" p-6 border-b border-gray-800 text-[#babbbe]">
                                    <IoFish />
                                </button>
                            </li>{" "}
                            <li className=" mx-auto items-center text-3xl">
                                <button className=" p-6 border-b border-gray-800 text-[#babbbe]">
                                    <GiShrimp />
                                </button>
                            </li>{" "}
                            <li className=" mx-auto items-center text-2xl">
                                <button className=" p-6 border-b border-gray-800 text-[#babbbe]">
                                    <IoWineSharp />
                                </button>
                            </li>{" "}
                            <li className=" mx-auto  items-center text-2xl">
                                <button className=" p-6 pt-[60px] border-b border-gray-800 text-[#babbbe]">
                                    <LuCakeSlice />
                                </button>
                            </li>{" "}
                            <li className=" mx-auto items-center text-2xl">
                                <button className=" pt-6 pb-7 border-b border-gray-800 text-[#babbbe]">
                                    <FaBellConcierge />
                                </button>
                            </li>
                            {/*
                            <li className=" mx-auto items-center text-4xl">
                                <LuBeef />
                            </li>
                            <li className=" mx-auto items-center text-4xl">
                                <FiMenu />
                            </li>
                            <li className=" mx-auto items-center text-4xl">
                                <FaStar />
                            </li>
                            <li className=" mx-auto items-center text-4xl">
                                <BiSolidBowlHot />
                            </li>
                            <li className=" mx-auto items-center text-4xl">
                                <LuBeef />
                            </li> */}
                        </ul>
                    </div>{" "}
                    <div>{children} </div>
                </div>
            </body>
        </html>
    );
}
